version: '3'
services:
  ayomidebakare_service:
    build: .
    image: ayomidebakare
    container_name: ayomidebakare_main
    stdin_open: true
    tty: true
    ports:
      - 5553:5553
      - 5552:5552
    networks:
      - main_network
    volumes:
      - .:/ayomidebakare.site

networks:
  main_network:
    driver: bridge
